### ISSUE TITLE
python 3.5 关于除法末尾数字的问题

### ISSUE THREAD

**Issue by AntiTopQuark** [NEUMSC/Q-A#4]
### System and toolchain version

- python 3.5

### Expected behavior
输出的数据可以四舍五入，如10/3=3.33333333333

### Actual behavior
>>>10/3
3.3333333333333335

### Steps to reproduce the behavior
···
>>> 1/3
0.3333333333333333
>>> 1/3
0.3333333333333333
>>> 5/3
1.6666666666666667
>>> 7/3
2.3333333333333335
>>> 10/3
3.3333333333333335
>>> 8/3
2.6666666666666665
>>> 11/3
3.6666666666666665
>>> 22/3
7.333333333333333
···

**Comment by xiahaoyun** [comment]
[浮点数算法：争议和限制](http://www.pythondoc.com/pythontutorial3/floatingpoint.html)

不知道有没有帮助

**Comment by xjkdev** [comment]
赞同楼上，附上原文：
[15. Floating Point Arithmetic: Issues and Limitations](https://docs.python.org/3/tutorial/floatingpoint.html)
